### ISSUE TITLE
SparseLogisticRegressionWithBFGS on Tencent dataset usage?

### ISSUE THREAD

**Issue by fanshiqing** [intel-analytics/SparseML#10]
I plan to use SparseML's SparseLogisticRegressionWithBFGS API to test Tencent dataset so that I can compare the performance with Parameter Server's LR implementation.

After simply referring to the SparseML/examples dir, I guess the core SparseML's LR application code is as follows:

```
val lr = new SparseLogisticRegressionWithLBFGS()
      .setNumClasses(numClasses)
lr.optimizer.setNumIterations(numIterations)
val model = lr.run(trainingData)
```

I took these and ran test on tencent dataset on Gondolin 8-node-cluster but always get **Exexutor time out** problem and after carefully check I'm sure that the cluster nodes is okay.

After simply looking through the [SparseLogisticRegressionWithBFGS](https://github.com/intel-analytics/SparseML/blob/master/LogisticRegression/sparseLR_2.0/SparseLogisticRegressionWithLBFGS.scala) calling tree I found that following code:

```
override private def run(input: RDD[LabeledPoint], initialWeights: Vector, userSuppliedWeights: Boolean):
  LogisticRegressionModel = {
    // ml's Logistic regression only supports binary classification currently.
    if (numOfLinearPredictor == 1) {
      log.info("numOfLinearPredictor == 1")
//      def runWithMlLogisitcRegression(elasticNetParam: Double) = {
//        // Prepare the ml LogisticRegression based on our settings
//        val lr = new org.apache.spark.ml.classification.LogisticRegression()
//        lr.setRegParam(optimizer.getRegParam())
//        lr.setElasticNetParam(elasticNetParam)
//        lr.setStandardization(useFeatureScaling)
//        if (userSuppliedWeights) {
//          val uid = Identifiable.randomUID("logreg-static")
//          lr.setInitialModel(new org.apache.spark.ml.classification.LogisticRegressionModel(
//            uid, initialWeights.asML, 1.0))
//        }
//        lr.setFitIntercept(addIntercept)
//        lr.setMaxIter(optimizer.getNumIterations())
//        lr.setTol(optimizer.getConvergenceTol())
//        // Convert our input into a DataFrame
//        val sqlContext = new SQLContext(input.context)
//        import sqlContext.implicits._
//        val df = input.map(_.asML).toDF()
//        // Determine if we should cache the DF
//        val handlePersistence = input.getStorageLevel == StorageLevel.NONE
//        // Train our model
//        val mlLogisticRegresionModel = lr.train(df, handlePersistence)
//        // convert the model
//        val weights = Vectors.dense(mlLogisticRegresionModel.coefficients.toArray)
//        createModel(weights, mlLogisticRegresionModel.intercept)
//      }
//      optimizer.getUpdater() match {
//        case x: SquaredL2Updater => runWithMlLogisitcRegression(0.0)
//        case x: L1Updater => runWithMlLogisitcRegression(1.0)
//        case _ => super.run(input, initialWeights)
//      }
      super.run(input, initialWeights)
    } else {
      log.info("numOfLinearPredictor != 1")
      super.run(input, initialWeights)
    }
```

 did nothing but simply calling spark-mllib-2.10's `run` method.

So my question is: 
- 1. My idea is right or not? if not, what the right usage of SparseML's sparseLR algorithm?  
- 2. if the usage is okay, so what's the optimization of `SparseML's SparseLogisticRegressionWithBFGS`?

Thanks advance for any help and advice!

@dding3

**Comment by dding3** [comment]
For 1, Please refer [LogisticRegressionExample.scala](https://github.com/intel-analytics/WebScaleML/blob/master/examples/src/main/scala/com/intel/webscaleml/logisticRegression/LogisticRegressionExample.scala) . We didn't migrate it here to avoid duplicate lr example.

For SparseLogisticRegressionWithLBFGS class, you may need help from @hhbyyh .

**Comment by fanshiqing** [comment]
@zhichao-li To refer [LogisticRegressionExample.scala](https://github.com/intel-analytics/WebScaleML/blob/master/examples/src/main/scala/com/intel/webscaleml/logisticRegression/LogisticRegressionExample.scala), perhaps I need access to the **WebScaleML** project.
